COMMON: &COMMON
category:
  '01': "フード・ドリンク"
  '02': "ブランド"
  '03': "ファッション"
  '04': "AV・デジモノ"
  '05': "家電"
  '06': "美容・コスメ"
  '07': "ダイエット・健康"
  '08': "生活雑貨"
  '09': "ホビー・エトセトラ"
  '10': "スポーツ・レジャー"
  jun:  "JUNゼミ"
  all:  "全商品"
