COMMON: &COMMON
category:
  '01': "フード・ドリンク・スイーツ"
  '02': "ファッション"
  '03': "AV・デジモノ"
  '04': "家電"
  '05': "美容・コスメ"
  '06': "ダイエット・健康"
  '07': "生活用品・インテリア・雑貨"
  '08': "スポーツ・レジャー"
  '09': "ホビー・エトセトラ"
  jun:  "JUNゼミ"
  all:  "全商品"
